"""Canonical colours, and the one alias map that reconciles them.

Two palettes, because there are two authorities and they answer different
questions.

:data:`ATLAS` is the finer-grained one: 46 entries with deliberate
within-lineage shading, covering the cell types the HTAN and IMC data
distinguish. It is the default for figures about input data.

:data:`SIMULATION` mirrors ``kCellTypeColors`` in ``custom.cpp`` exactly. Those
21 CSS colour names drive the SVG movie frames and PhysiCell-Studio, and
``sanity_checks/check_cell_colors.py`` guards them -- its docstring records two
occasions when the palette silently drifted. Use it for any figure meant to sit
beside a movie frame, so the static panel and the animation agree.

They do not share a vocabulary: the simulation says ``epithelial_tumor``,
``B cell``, ``macrophage`` where the atlas says ``epithelial``, ``B``,
``Macrophage``. :func:`normalize` reconciles that in one place rather than at
each call site.
"""

__all__ = [
    "GLASBEY_DARK",
    "categorical",
    "ATLAS",
    "SIMULATION",
    "ANTIGEN_CLASS",
    "PATIENT",
    "PALETTES",
    "MISSING_COLOR",
    "normalize",
    "colors_for",
]

#: Only reached when strict lookup is turned off. The scripts this replaces
#: returned grey silently, which is how four missing cell types went unnoticed.
MISSING_COLOR = "#aaaaaa"

#: Glasbey dark, 256 maximally distinguishable colours against a light ground.
#:
#: Vendored from colorcet rather than imported. colorcet is not installed in
#: physicell-sim-260606 and that environment cannot currently take new packages
#: -- its pyqt / qt-main stack no longer re-solves -- so a hard dependency would
#: make pdacagviz uninstallable exactly where it is used. The values are a fixed
#: published constant, so vendoring carries no drift risk the way vendoring code
#: would.
#:
#: Source: colorcet 3.2.1, `colorcet.glasbey_dark`. Generated by the method of
#: Glasbey et al., which maximises perceptual distance between successive
#: entries, so a palette truncated to the first N is still well separated --
#: which is what makes it the right default when the category count is unknown.
#: colorcet is CC-BY 4.0; attribution is this comment.
GLASBEY_DARK = [
    "#d60000", "#8c3bff", "#018700", "#00acc6", "#e6a500", "#ff7ed1",
    "#6b004f", "#573b00", "#005659", "#15e18c", "#0000dd", "#a17569",
    "#bcb6ff", "#bf03b8", "#645472", "#790000", "#0774d8", "#729a7c",
    "#ff7752", "#004b00", "#8e7b01", "#f2007b", "#8eba00", "#a57bb8",
    "#5901a3", "#e2afaf", "#a03a52", "#a1c8c8", "#9e4b00", "#546744",
    "#bac389", "#5e7b87", "#60383b", "#8287ff", "#380000", "#e252ff",
    "#2f5282", "#7ecaff", "#c4668e", "#008069", "#919eb6", "#cc7407",
    "#7e2a8e", "#00bda3", "#2db152", "#4d33ff", "#00e400", "#ff00cd",
    "#c85748", "#e49cff", "#1ca1ff", "#6e70aa", "#c89a69", "#77563b",
    "#03dae6", "#c1a3c3", "#ff6989", "#ba00fd", "#915280", "#9e0174",
    "#93a14f", "#364424", "#af6dff", "#596d00", "#ff3146", "#828056",
    "#006d2d", "#8956af", "#5949a3", "#773416", "#85c39a", "#5e1123",
    "#d48580", "#a32818", "#0087b1", "#ca0044", "#ffa056", "#eb4d00",
    "#6b9700", "#528549", "#755900", "#c8c33f", "#91d370", "#4b9793",
    "#4d230c", "#60345b", "#8300cf", "#8a0031", "#9e6e31", "#ac8399",
    "#c63189", "#015438", "#086b83", "#87a8eb", "#6466ef", "#c35dba",
    "#019e70", "#805059", "#826e8c", "#b3bfda", "#b89028", "#ff97b1",
    "#a793e1", "#698cbd", "#4b4f01", "#4801cc", "#60006e", "#446966",
    "#9c5642", "#7bacb5", "#cd83bc", "#0054c1", "#7b2f4f", "#fb7c00",
    "#34bf00", "#ff9c87", "#e1b669", "#526077", "#5b3a7c", "#eda5da",
    "#ef52a3", "#5d7e69", "#c3774f", "#d14867", "#6e00eb", "#1f3400",
    "#c14103", "#6dd4c1", "#46709e", "#a101c3", "#0a8289", "#afa501",
    "#a55b6b", "#fd77ff", "#8a85ae", "#c67ee8", "#9aaa85", "#876bd8",
    "#01baf6", "#af5dd1", "#59502a", "#b5005e", "#7cb569", "#4985ff",
    "#00c182", "#d195aa", "#a34ba8", "#e205e2", "#16a300", "#382d00",
    "#832f33", "#5d95aa", "#590f00", "#7b4600", "#6e6e31", "#335726",
    "#4d60b5", "#a19564", "#623f28", "#44d457", "#70aacf", "#2d6b4d",
    "#72af9e", "#fd1500", "#d8b391", "#79893b", "#7cc6d8", "#db9036",
    "#eb605d", "#eb5ed4", "#e47ba7", "#a56b97", "#009744", "#ba5e21",
    "#bcac52", "#87d82f", "#873472", "#aea8d1", "#e28c62", "#d1b1eb",
    "#36429e", "#3abdc1", "#669c4d", "#9e0399", "#4d4d79", "#7b4b85",
    "#c33431", "#8c6677", "#aa002d", "#7e0175", "#01824d", "#724967",
    "#727790", "#6e0099", "#a0ba52", "#e16e31", "#c46970", "#6d5b95",
    "#a33b74", "#316200", "#87004f", "#335769", "#ba8c7c", "#1859ff",
    "#909101", "#2b8ad4", "#1626ff", "#21d3ff", "#a390af", "#8a6d4f",
    "#5d213d", "#db03b3", "#6e56ca", "#642821", "#ac7700", "#a3bff6",
    "#b58346", "#9738db", "#b15093", "#7242a3", "#878ed1", "#8970b1",
    "#6baf36", "#5979c8", "#c69eff", "#56831a", "#00d6a7", "#824638",
    "#11421c", "#59aa75", "#905b01", "#f64470", "#ff9703", "#e14231",
    "#ba91cf", "#34574d", "#f7807c", "#903400", "#b3cd00", "#2d9ed3",
    "#798a9e", "#50807c", "#c136d6", "#eb0552", "#b8ac7e", "#487031",
    "#839564", "#d89c89", "#0064a3", "#4b9077", "#8e6097", "#ff5238",
    "#a7423b", "#006e70", "#97833d", "#dbafc8",
]


#: 46 cell types, hex, with within-lineage shading (iCAF / myCAF / apCAF read
#: as one family). Source of truth for figures about HTAN and IMC input data.
ATLAS = {
    "CD8_Tcell": "#8B0000",
    "CD4_Tcell": "#FFA500",
    "Treg": "#C8A2C8",
    "CD8_exhausted": "#FA8072",
    "PDAC": "#00CED1",
    "PDAC_unclassified": "#48D1CC",
    "epithelial": "#DA70D6",
    "epithelial_class1": "#C060C0",
    "epithelial_class2": "#B040B0",
    "epithelial_class1_class2": "#9020A0",
    "mesenchymal": "#7FFF00",
    "mesenchymal_class1": "#66CC00",
    "mesenchymal_class2": "#4D9900",
    "mesenchymal_class1_class2": "#336600",
    "epithelial_mesenchymal": "#7C3AED",
    "epithelial_mesenchymal_class1": "#6A30D0",
    "epithelial_mesenchymal_class2": "#5820B0",
    "epithelial_mesenchymal_class1_class2": "#461090",
    "PanIN_early": "#b0d4f1",
    "PanIN_late": "#5b9bd5",
    "ADM": "#2e75b6",
    "Acinar": "#1f4e79",
    "Acinar_REG+": "#16365c",
    "Duct_like_1": "#9dc3e6",
    "Duct_like_2": "#6baed6",
    "CAF": "#f4a460",
    "iCAF": "#e8891a",
    "myCAF": "#c46e10",
    "apCAF": "#a05208",
    "CXCR4+_iCAF": "#d4a96a",
    "CD133+_iCAF": "#bf8040",
    "B": "#74c476",
    "Plasma": "#41ab5d",
    "NK": "#238b45",
    "Macrophage": "#005a32",
    "Monocyte": "#a8ddb5",
    "Mast": "#ccebc5",
    "Neutrophil": "#e5f5e0",
    "cDC1": "#78c679",
    "cDC2": "#31a354",
    "other_immune": "#bdbdbd",
    "Endothelial": "#9ecae1",
    "Islet": "#4292c6",
    "Erythrocyte": "#fc9272",
    "Tuft": "#fdae6b",
    "other_tissue": "#d9d9d9",
}

#: Mirrors kCellTypeColors in custom.cpp. Keep byte-identical to it: these are
#: the colours PhysiCell paints, and a figure using them matches its movie.
#: sanity_checks/check_cell_colors.py should assert this equality.
SIMULATION = {
    "epithelial_normal": "palegreen",
    "mesenchymal_normal": "lightcyan",
    "CAF": "yellow",
    "epithelial_tumor": "green",
    "mesenchymal_tumor": "blue",
    "other_tissue": "magenta",
    "CD4_Tcell": "darkorange",
    "CD8_Tcell": "maroon",
    "Treg": "plum",
    "CD8_exhausted": "lightcoral",
    "B cell": "papayawhip",
    "macrophage": "lightpink",
    "epithelial_tumor_class1": "chartreuse",
    "epithelial_tumor_class1_class2": "darkolivegreen",
    "epithelial_tumor_class2": "seagreen",
    "mesenchymal_tumor_class1": "lightskyblue",
    "mesenchymal_tumor_class1_class2": "dodgerblue",
    "mesenchymal_tumor_class2": "royalblue",
    "apCAF": "grey",
    "PDAC_unclassified": "white",
    "duct_filler": "tan",
}

#: Antigen class. This is the plotting/ variant, kept over the analysis/ one,
#: which reused three tumour-lineage colours (#00CED1 PDAC, #DA70D6 epithelial,
#: #7FFF00 mesenchymal) and so double-encoded any figure showing both.
ANTIGEN_CLASS = {
    "class I+II": "#1f78b4",
    "class I": "#a6cee3",
    "class II": "#e31a1c",
    "none": "#d9d9d9",
}

#: Per-patient colours, assigned from GLASBEY_DARK in simulation order.
#:
#: Replaces an 8-entry hand-picked table carried over from
#: plot_antigen_comparison.py. The htan_wellmixed simulations span 21
#: patients, 7 of which appeared in that table -- a partial match, so strict
#: lookup raised rather than quietly greying out the other 14. Correct
#: behaviour, and it named the gap this closes.
#:
#: Hand-picking 21 distinguishable colours is not something to do by eye,
#: which is what glasbey is for. Order follows simulation id, so the mapping is
#: reproducible from the CSV rather than depending on set iteration order.
PATIENT = {
    "HT056": "#d60000",
    "HT060": "#8c3bff",
    "HT061": "#018700",
    "HT064": "#00acc6",
    "HT071": "#e6a500",
    "HT085": "#ff7ed1",
    "HT115": "#6b004f",
    "HT121": "#573b00",
    "HT122": "#005659",
    "HT123": "#15e18c",
    "HT124": "#0000dd",
    "HT125": "#a17569",
    "HT138": "#bcb6ff",
    "HT140": "#bf03b8",
    "HT166": "#645472",
    "HT168": "#790000",
    "HT185": "#0774d8",
    "HT190": "#729a7c",
    "HT191": "#ff7752",
    "HT200": "#004b00",
    "HT204": "#8e7b01",
}

#: Palettes addressable by name, which is what settings.palette holds.
PALETTES = {
    "atlas": ATLAS,
    "simulation": SIMULATION,
    "antigen_class": ANTIGEN_CLASS,
    "patient": PATIENT,
}

#: Simulation vocabulary -> atlas vocabulary. Only the names that actually
#: differ; anything absent is already spelled the same in both.
_ALIASES = {
    "epithelial_tumor": "epithelial",
    "epithelial_tumor_class1": "epithelial_class1",
    "epithelial_tumor_class2": "epithelial_class2",
    "epithelial_tumor_class1_class2": "epithelial_class1_class2",
    "mesenchymal_tumor": "mesenchymal",
    "mesenchymal_tumor_class1": "mesenchymal_class1",
    "mesenchymal_tumor_class2": "mesenchymal_class2",
    "mesenchymal_tumor_class1_class2": "mesenchymal_class1_class2",
    "B cell": "B",
    "macrophage": "Macrophage",
    "epithelial_normal": "epithelial",
    "mesenchymal_normal": "mesenchymal",
}


def categorical(n):
    """First ``n`` colours of :data:`GLASBEY_DARK`, cycling if more are asked for.

    The default for any categorical variable with no semantic palette of its own
    -- a condition, a treatment arm, a patient. Glasbey orders its entries by
    decreasing perceptual distance, so a prefix of the list is the best available
    separation for that many categories, which is the property matplotlib's
    ten-colour cycle lacks the moment there are eleven groups.
    """
    if n <= 0:
        return []
    if n <= len(GLASBEY_DARK):
        return list(GLASBEY_DARK[:n])
    reps = -(-n // len(GLASBEY_DARK))
    return (GLASBEY_DARK * reps)[:n]


def normalize(name):
    """Map a simulation cell-type name onto its atlas spelling.

    Names already in atlas form pass through unchanged, so this is safe to
    apply to a mixed column without checking where each value came from.
    """
    return _ALIASES.get(name, name)


def colors_for(names, palette=None, strict=None, as_dict=False):
    """Look up colours for cell-type names.

    Parameters
    ----------
    names
        Iterable of cell-type names, in either vocabulary.
    palette
        Palette name or an explicit mapping. Defaults to ``settings.palette``.
    strict
        Raise on a name with no colour. Defaults to ``settings.strict_palette``.
        Turning it off substitutes :data:`MISSING_COLOR`, which is convenient
        for a quick look and dangerous for anything published -- a grey bar
        looks like a real category rather than a missing entry.
    as_dict
        Return ``{name: colour}`` instead of a list in input order.

    Raises
    ------
    KeyError
        Under strict lookup, naming every unmapped value at once rather than
        failing on the first, so one run tells you everything to add.
    """
    from .settings import settings

    if palette is None:
        palette = settings.palette
    if strict is None:
        strict = settings.strict_palette

    if isinstance(palette, str):
        if palette not in PALETTES:
            known = ", ".join(sorted(PALETTES))
            raise ValueError(f"unknown palette {palette!r}; expected one of: {known}")
        table = PALETTES[palette]
    else:
        table = dict(palette)

    names = list(names)
    resolved, missing = {}, []
    for name in names:
        colour = table.get(name, table.get(normalize(name)))
        if colour is None:
            missing.append(name)
            colour = MISSING_COLOR
        resolved[name] = colour

    if missing and strict:
        raise KeyError(
            f"no colour for {len(missing)} name(s) in the "
            f"{palette if isinstance(palette, str) else 'given'} palette: "
            f"{', '.join(map(repr, sorted(set(missing))))}. "
            "Add them, pick another palette, or pass strict=False to accept grey."
        )

    if as_dict:
        return resolved
    return [resolved[name] for name in names]
