# run_wellmixed_imc.jl
# -----------------------------------------------------------------------------
# Well-mixed driver that pulls per-ROI cell counts from the JHH IMC samples,
# the IMC counterpart of run_wellmixed_htan_singlecell.jl.
#
# Counts come from assignmentsummary_JHH_IMC.csv (generated by
# make_imc_count_summary.py). Unlike assignmentsummary_HTAN_singlecell.csv, its
# columns are ALREADY PhysiCell cell-type names, so no Pattern2/Pattern7 remap is
# needed -- each type column maps 1:1 to an annulus patch in cells.xml.
#
# "Well-mixed": only cell counts vary; every type is scattered uniformly on the
# default annulus (inner=0, outer=400). Types absent from the IMC summary stay at
# their cells.xml default of number=0.
# -----------------------------------------------------------------------------

# g++ compiler is machine dependent
# ENV["PHYSICELL_CPP"] = "g++-15"
ENV["PHYSICELL_CPP"] = "g++"

using PhysiCellModelManager
using CSV, DataFrames

initializeModelManager(
    joinpath(@__DIR__, "PhysiCell"),
    joinpath(@__DIR__, "data")
)

df = CSV.read(joinpath(@__DIR__, "assignmentsummary_JHH_IMC_test.csv"), DataFrame)

inputs = InputFolders(
    "antigen_presentation_htan_singlecell",   # config
    "antigen_presentation_htan_singlecell";   # custom_code
    rulesets_collection = "antigen_presentation_htan_singlecell",
    ic_cell = "antigen_presentation_htan_singlecell"
)

# All columns except these bookkeeping ones are cell-type count columns; each
# name must match a <cell_patches name=...> entry in the well-mixed cells.xml.
bookkeeping = ["sample_id", "total"]
cell_types = filter(n -> !(n in bookkeeping), names(df))

for row in eachrow(df)
    sample = row.sample_id

    # ECM initial condition on, matching the original well-mixed driver.
    dvs = DiscreteVariation[DiscreteVariation(configPath("ecm", "initial_condition"), 1)]

    for ct in cell_types
        n = round(Int, row[ct])
        push!(dvs, DiscreteVariation(icCellsPath(ct, "annulus", 1, "number"), n))
    end

    cv = CoVariation(dvs...)

    println("Running $sample  ($(round(Int, row.total)) cells across $(length(cell_types)) types)")
    monad = createTrial(inputs, cv; n_replicates=1, use_previous=false)
    PhysiCellModelManager.run(monad)
end
