# run_wellmixed_imc.jl
# -----------------------------------------------------------------------------
# Well-mixed driver that pulls per-ROI cell counts from the JHH IMC samples,
# the IMC counterpart of run_wellmixed_htan_singlecell.jl.
#
# Counts come from assignmentsummary_JHH_IMC.csv (generated by
# make_imc_count_summary.py). Unlike assignmentsummary_HTAN_singlecell.csv, its
# columns are ALREADY PhysiCell cell-type names, so no Pattern2/Pattern7 remap is
# needed -- each type column maps 1:1 to an annulus patch in cells.xml.
#
# "Well-mixed": only cell counts vary; every type is scattered uniformly on the
# default annulus (inner=0, outer=400). Types absent from the IMC summary stay at
# their cells.xml default of number=0.
# -----------------------------------------------------------------------------

# g++ compiler is machine dependent
# ENV["PHYSICELL_CPP"] = "g++-15"
ENV["PHYSICELL_CPP"] = "g++"

using PhysiCellModelManager
using CSV, DataFrames

initializeModelManager(
    joinpath(@__DIR__, "PhysiCell"),
    joinpath(@__DIR__, "data")
)

# Determine the SLURM account to bill jobs to: pull this user's associated
# accounts from sacctmgr and use the first one listed. Set
# ENV["PCMM_SLURM_ACCOUNT"] to override.
function slurmAccount()
    haskey(ENV, "PCMM_SLURM_ACCOUNT") && return ENV["PCMM_SLURM_ACCOUNT"]
    username = readchomp(`whoami`)
    accounts = split(readchomp(`sacctmgr -n -P show assoc user=$username format=account`), "\n"; keepempty=false)
    isempty(accounts) && error("No SLURM account found for user $username. Set ENV[\"PCMM_SLURM_ACCOUNT\"] explicitly.")
    return accounts[1]
end

# Submit simulations to SLURM instead of running them locally.
useHPC(true)
setJobOptions(Dict(
    "cpus-per-task" => "1",
    "mem" => "2.5G",
    "time" => "7-00:00:00",
    "account" => slurmAccount(),
))
setNumberOfParallelSims(50)

df = CSV.read(joinpath(@__DIR__, "assignmentsummary_JHH_IMC_test.csv"), DataFrame)

inputs = InputFolders(
    "antigen_presentation_htan_singlecell",   # config
    "antigen_presentation_htan_singlecell";   # custom_code
    rulesets_collection = "antigen_presentation_htan_singlecell",
    ic_cell = "antigen_presentation_htan_singlecell"
)

# All columns except these bookkeeping ones are cell-type count columns; each
# name must match a <cell_patches name=...> entry in the well-mixed cells.xml.
bookkeeping = ["sample_id", "total"]
cell_types = filter(n -> !(n in bookkeeping), names(df))

# Build every sample's monad up front (no jobs submitted yet), then run them
# all together in one Trial so the worker pool (see setNumberOfParallelSims
# above) can submit up to that many simulations concurrently instead of
# waiting for each sample's job to finish before starting the next.
monads = []
for row in eachrow(df)
    sample = row.sample_id

    # ECM initial condition on, matching the original well-mixed driver.
    dvs = DiscreteVariation[DiscreteVariation(configPath("ecm", "initial_condition"), 1)]

    for ct in cell_types
        n = round(Int, row[ct])
        push!(dvs, DiscreteVariation(icCellsPath(ct, "annulus", 1, "number"), n))
    end

    cv = CoVariation(dvs...)

    println("Queuing $sample  ($(round(Int, row.total)) cells across $(length(cell_types)) types)")
    push!(monads, createTrial(inputs, cv; n_replicates=1, use_previous=false))
end

trial = createTrial(monads)
PhysiCellModelManager.run(trial)
